# Generated by Django 4.2.4 on 2023-09-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Operative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("phone_number", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=200)),
                ("job_description", models.TextField()),
                ("job_location", models.CharField(max_length=200)),
                ("notes", models.TextField()),
                ("job_date", models.DateField(null=True)),
                ("job_created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
