# Generated by Django 4.2.4 on 2023-09-13 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("operatives", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Details",
            fields=[
                ("address", models.CharField(max_length=200)),
                ("phone_number", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=200)),
                ("trade", models.TextField()),
                ("cards", models.CharField(max_length=200)),
                ("driving_license", models.CharField(max_length=200)),
                ("wage", models.IntegerField()),
                (
                    "operative",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="operatives.operative",
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="operative",
            old_name="job_created_at",
            new_name="operative_created_at",
        ),
        migrations.RemoveField(
            model_name="operative",
            name="email",
        ),
        migrations.RemoveField(
            model_name="operative",
            name="job_date",
        ),
        migrations.RemoveField(
            model_name="operative",
            name="job_description",
        ),
        migrations.RemoveField(
            model_name="operative",
            name="job_location",
        ),
        migrations.RemoveField(
            model_name="operative",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="operative",
            name="phone_number",
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=200)),
                ("job_created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "operative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="operatives.operative",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Dates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_date", models.DateField(null=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="operatives.job"
                    ),
                ),
            ],
        ),
    ]
