# Generated by Django 4.2.4 on 2023-09-13 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("operatives", "0002_details_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Dates",
            new_name="Date",
        ),
    ]
