# Generated by Django 4.2.4 on 2023-09-13 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("operatives", "0003_rename_dates_date"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Details",
            new_name="Detail",
        ),
        migrations.RenameField(
            model_name="detail",
            old_name="cards",
            new_name="card",
        ),
    ]
