# Generated by Django 4.2.4 on 2023-09-13 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("operatives", "0004_rename_details_detail_rename_cards_detail_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="date",
            name="operative",
            field=models.ForeignKey(
                default=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="operatives.operative",
            ),
        ),
    ]
