# Generated by Django 4.2.4 on 2023-09-14 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "operatives",
            "0006_job_job_date_alter_detail_trade_remove_job_operative_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="operative",
            new_name="operatives",
        ),
    ]
