# Generated by Django 4.2.4 on 2023-09-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operatives", "0007_rename_operative_job_operatives"),
    ]

    operations = [
        migrations.AddField(
            model_name="detail",
            name="post_code",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="detail",
            name="wage",
            field=models.PositiveIntegerField(),
        ),
    ]
