# Generated by Django 4.2.5 on 2023-09-24 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("operatives", "0009_job_post_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="job",
            options={"ordering": ["location"]},
        ),
        migrations.AlterModelOptions(
            name="operative",
            options={"ordering": ["first_name"]},
        ),
    ]
