# Generated by Django 4.2.5 on 2023-09-24 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("operatives", "0011_rename_operatives_job_operative"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="operative",
            new_name="operatives",
        ),
    ]
