# Generated by Django 4.2.5 on 2023-09-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operatives", "0012_rename_operative_job_operatives"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detail",
            name="address",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="detail",
            name="email",
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="detail",
            name="post_code",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="post_code",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
