# Generated by Django 4.2.5 on 2023-11-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operatives", "0013_alter_detail_address_alter_detail_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="operative",
            name="rating",
            field=models.CharField(
                choices=[
                    ("Poor", "Poor"),
                    ("Room for Improvement", "Room for Improvement"),
                    ("Good", "Good"),
                    ("Dog's bollocks", "Dog's bollocks"),
                ],
                default="Poor",
                max_length=21,
            ),
        ),
    ]
