# Generated by Django 4.2.5 on 2023-11-28 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operatives", "0015_alter_job_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operative",
            name="rating",
            field=models.CharField(
                choices=[
                    ("McDonalds", "McDonalds"),
                    ("Room for Improvement", "Room for Improvement"),
                    ("Valuable", "Valuable"),
                    ("Five Star", "Five Star"),
                ],
                default="Valuable",
                max_length=21,
            ),
        ),
    ]
