# Generated by Django 4.2.5 on 2023-11-15 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_rename_store_material"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="material",
            options={"ordering": ["inventory", "title"]},
        ),
    ]
