# Generated by Django 4.2.4 on 2023-09-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snags", "0002_snag_creatd_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="snag",
            name="creatd_at",
        ),
        migrations.AlterField(
            model_name="snag",
            name="notes",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="snag",
            name="phone_number",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="snag",
            name="snag_details",
            field=models.TextField(),
        ),
    ]
