# Generated by Django 4.2.4 on 2023-09-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snags", "0003_remove_snag_creatd_at_alter_snag_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="snag",
            name="booked_date",
            field=models.DateField(null=True),
        ),
    ]
