# Generated by Django 4.2.4 on 2023-09-03 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snags", "0004_snag_booked_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="snag",
            name="status",
            field=models.CharField(
                choices=[("O", "Open"), ("C", "Closed"), ("D", "Waiting for delivery")],
                default="O",
                max_length=1,
            ),
        ),
    ]
