# Generated by Django 4.2.4 on 2023-09-05 19:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("snags", "0005_snag_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="snag",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
