# Generated by Django 4.2.4 on 2023-09-05 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snags", "0006_snag_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="snag",
            name="status",
            field=models.CharField(
                choices=[
                    ("Open", "Open"),
                    ("Close", "Closed"),
                    ("Waiting for Parts", "Waiting for Parts"),
                ],
                default="Open",
                max_length=20,
            ),
        ),
    ]
