# Generated by Django 4.2.5 on 2023-09-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snags", "0010_snag_am_pm_alter_snag_site"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="snag",
            options={"ordering": ["booked_date"]},
        ),
        migrations.AlterField(
            model_name="snag",
            name="status",
            field=models.CharField(
                choices=[
                    ("Open", "Open"),
                    ("Closed", "Closed"),
                    ("Parts required", "Parts required"),
                ],
                default="Open",
                max_length=20,
            ),
        ),
    ]
