# Generated by Django 4.2.5 on 2023-09-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snags", "0011_alter_snag_options_alter_snag_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="snag",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="snag",
            name="site",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="snag",
            name="snag_details",
            field=models.TextField(blank=True, null=True),
        ),
    ]
