# Generated by Django 4.2.5 on 2023-10-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snags", "0012_alter_snag_notes_alter_snag_site_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="snag",
            name="am_pm",
            field=models.CharField(
                choices=[("AM", "AM"), ("Any time", "PM"), ("Any time", "Any time")],
                default="AM",
                max_length=10,
            ),
        ),
    ]
