# Generated by Django 4.2.5 on 2023-11-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snags", "0014_snag_completition_date_snag_fnh_ref_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="snag",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
